name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t saurabhkharate/reactjs-app-test .

      - name: Publish image to Docker Hub
        run: docker push saurabhkharate/reactjs-app-test:latest

  deploy:
    needs: build
    runs-on: aws-ec2 
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull saurabhkharate/reactjs-app-test:latest

      - name: Delete Old Container
        run: docker rm -f reactContainer

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactContainer saurabhkharate/reactjs-app-test
